### ISSUE TITLE
cant find windows release

### ISSUE THREAD

**Issue by crazycrixar** [Bixilon/Minosoft#17]
what the title says

**Comment by Bixilon** [comment]
See https://github.com/Bixilon/Minosoft/actions/runs/6203783934

**Comment by Bluscream** [comment]
> https://nightly.link/Bixilon/Minosoft/workflows/build/master?preview

|                         |                                                                                          |
|-------------------------|------------------------------------------------------------------------------------------|
| minosoft-macos-latest   | https://nightly.link/Bixilon/Minosoft/workflows/build/master/minosoft-macos-latest.zip   |
| minosoft-ubuntu-latest  | https://nightly.link/Bixilon/Minosoft/workflows/build/master/minosoft-ubuntu-latest.zip  |
| minosoft-windows-latest | https://nightly.link/Bixilon/Minosoft/workflows/build/master/minosoft-windows-latest.zip |
