### ISSUE TITLE
mac os realease umm i think you already mentioned it wasn't finished tho sorry (ignore this issue)

### ISSUE THREAD

**Issue by crazycrixar** [Bixilon/Minosoft#18]
as the title says

**Comment by lesoup-mxd** [comment]
Please don't ping everyone for this, I am sure you can contact the publishers

**Comment by crazycrixar** [comment]
> Please don't ping everyone for this, I am sure you can contact the publishers

yes sorry how do you delete issue?

**Comment by Bixilon** [comment]
macOS support is complete (see https://gitlab.bixilon.de/bixilon/minosoft/-/issues/29). If you need an arm build, do it yourself. GitHub does not support mac os on arm, so it won't build (though it would be possible by providing `-Parchitecture=arm -Pplatform=mac` as gradle arguments).


@lesoup-mxd You are not pinged directly, you are watching that repository (and that means you get all issues and all comments per email as everyone else)

But yes, @crazycrixar that is not really an issue, consider asking on https://matrix.to/#/#minosoft:matrix.org in the future.
