### ISSUE TITLE
Building for windows fails

### ISSUE THREAD

**Issue by ilkerbey-01** [Bixilon/Minosoft#2]
https://github.com/ilkerbey-01/Minosoft/runs/6297426314?check_suite_focus=true

here is my VERY basic 2 line edit in code

**Comment by Bixilon** [comment]
Yes, natives detection is wrong on windows x64. Should be fixed with ca1c73293b7e2b8a616de5102f8b889d44d4b2ed

**Comment by ilkerbey-01** [comment]
https://github.com/ilkerbey-01/Minosoft/runs/6303405708?check_suite_focus=true

seems like fixed, thanks.
