### ISSUE TITLE
cant join cuberite/forge/vanilla 1.12.2 (localhost) server

### ISSUE THREAD

**Issue by skidd-level-100** [Bixilon/Minosoft#20]
----- Minosoft Crash Report -----
// Damn!

-- General information --
    Time: 2023-11-24 21:17:50(1700889470)
    Thread: JavaFX Application Thread
    Notes: Hard crash intended!

-- Stacktrace --
    java.lang.NullPointerException
    	at de.bixilon.minosoft.data.entities.entities.player.local.LocalPlayerEntity.<init>(LocalPlayerEntity.kt:45)
    	at de.bixilon.minosoft.protocol.network.connection.play.PlayConnection.connect(PlayConnection.kt:218)
    	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:201)
    	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:130)
    	at de.bixilon.minosoft.gui.eros.main.account.AccountController.checkAccount$lambda$7$lambda$6(AccountController.kt:123)
    	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
    	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
    	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
    	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)
    

-- Runtime details --
    Start arguments: []
    JVM flags: [-Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant]
    Environment: {PATH=/home/bumpsh/.scripts:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin, IMSETTINGS_MODULE=none, XAUTHORITY=/run/lightdm/bumpsh/xauthority, HISTCONTROL=ignoredups, XMODIFIERS=@im=none, GDMSESSION=i3, XDG_DATA_DIRS=/home/bumpsh/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop, GTK_IM_MODULE=gtk-im-context-simple, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, XDG_CURRENT_DESKTOP=i3, MAIL=/var/spool/mail/bumpsh, SSH_AGENT_PID=4306, COLORTERM=truecolor, LOGNAME=bumpsh, PWD=/home/bumpsh/git/Minosoft, WINDOWID=16777218, LESSOPEN=||/usr/bin/lesspipe.sh %s, SHELL=/bin/zsh, PAGER=less, OLDPWD=/home/bumpsh, ZSH=/home/bumpsh/.oh-my-zsh, XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0, DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/ , IMSETTINGS_INTEGRATE_DESKTOP=yes, LESS=-R, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:, XDG_SESSION_DESKTOP=i3, SHLVL=1, QT_IM_MODULE=xim, HISTSIZE=50000, I3SOCK=/run/user/1000/i3/ipc-socket.4100, TERM=alacritty, XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, LANG=en_US.utf8, XDG_SESSION_ID=2, XDG_SESSION_TYPE=x11, DISPLAY=:0, ALACRITTY_LOG=/tmp/Alacritty-95485.log, ALACRITTY_SOCKET=/run/user/1000/Alacritty-:0-95485.sock, CONDA_SHLVL=0, XDG_SESSION_CLASS=user, GDM_LANG=en_US.utf8, GTK3_MODULES=xapp-gtk3-module, LSCOLORS=Gxfxcxdxbxegedabagacad, XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/bumpsh, DESKTOP_SESSION=i3, USER=bumpsh, XDG_SEAT=seat0, SSH_AUTH_SOCK=/tmp/ssh-XXXXXXnNT1j3/agent.4100, EDITOR=/usr/bin/nano, HOSTNAME=fedora, ALACRITTY_WINDOW_ID=16777218, XDG_RUNTIME_DIR=/run/user/1000, XDG_VTNR=1, HOME=/home/bumpsh}
    Home directory: /home/bumpsh/.local/share/minosoft
    Config directory: /home/bumpsh/.config/minosoft

-- System information --
    Operating system: Linux: Fedora 64bit
    Platform os: linux
    Platform architecture: amd64
    Java: 11.0.20+8 64bit
    Memory: 62 GiB
    Processor: 16x AMD Ryzen 7 5800H with Radeon Graphics

-- Graphic Cards --
    #0
        Name: GA107BM [GeForce RTX 3050 Ti Mobile]
        Device id: 0x25e0
        VRam: 4328521728
        Vendor: NVIDIA Corporation (0x10de)
        Version info: unknown

-- Connections --
    #0
        Id: 1
        Version: 1.12.2
        Account: Bumpsh
        Address: 127.0.0.1
        Brand: unknown
        Events: 3
        State: ERROR
        DefaultPacketMapping state: HANDSHAKE
        Compression threshold: -1
        Encrypted: false
        Was connected: false
        Rendering: false
        Error: java.lang.NullPointerException

-- Properties --
    Version name: ae7b15d
    Stable: false

-- Git --
    Commit: ae7b15de10be579ca6add2e4078e48b9dfdfb7f3
    Branch: master
    Dirty: false

**Comment by skidd-level-100** [comment]
----- Minosoft Crash Report -----
// Damn!

-- General information --
    Time: 2023-11-24 21:17:50(1700889470)
    Thread: JavaFX Application Thread
    Notes: Hard crash intended!

-- Stacktrace --
    java.lang.NullPointerException
    	at de.bixilon.minosoft.data.entities.entities.player.local.LocalPlayerEntity.<init>(LocalPlayerEntity.kt:45)
    	at de.bixilon.minosoft.protocol.network.connection.play.PlayConnection.connect(PlayConnection.kt:218)
    	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:201)
    	at de.bixilon.minosoft.gui.eros.main.play.server.ServerListController$connect$1.invoke(ServerListController.kt:130)
    	at de.bixilon.minosoft.gui.eros.main.account.AccountController.checkAccount$lambda$7$lambda$6(AccountController.kt:123)
    	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.run(ThreadPoolExecutor.kt:25)
    	at de.bixilon.kutil.concurrent.pool.ThreadPoolExecutor.execute(ThreadPoolExecutor.kt:44)
    	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.loop(ThreadPoolThread.kt:49)
    	at de.bixilon.kutil.concurrent.pool.threads.ThreadPoolThread.run(ThreadPoolThread.kt:31)
    

-- Runtime details --
    Start arguments: []
    JVM flags: [-Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant]
    Environment: {PATH=/home/bumpsh/.scripts:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin, IMSETTINGS_MODULE=none, XAUTHORITY=/run/lightdm/bumpsh/xauthority, HISTCONTROL=ignoredups, XMODIFIERS=@im=none, GDMSESSION=i3, XDG_DATA_DIRS=/home/bumpsh/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop, GTK_IM_MODULE=gtk-im-context-simple, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, XDG_CURRENT_DESKTOP=i3, MAIL=/var/spool/mail/bumpsh, SSH_AGENT_PID=4306, COLORTERM=truecolor, LOGNAME=bumpsh, PWD=/home/bumpsh/git/Minosoft, WINDOWID=16777218, LESSOPEN=||/usr/bin/lesspipe.sh %s, SHELL=/bin/zsh, PAGER=less, OLDPWD=/home/bumpsh, ZSH=/home/bumpsh/.oh-my-zsh, XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0, DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/ , IMSETTINGS_INTEGRATE_DESKTOP=yes, LESS=-R, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:, XDG_SESSION_DESKTOP=i3, SHLVL=1, QT_IM_MODULE=xim, HISTSIZE=50000, I3SOCK=/run/user/1000/i3/ipc-socket.4100, TERM=alacritty, XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, LANG=en_US.utf8, XDG_SESSION_ID=2, XDG_SESSION_TYPE=x11, DISPLAY=:0, ALACRITTY_LOG=/tmp/Alacritty-95485.log, ALACRITTY_SOCKET=/run/user/1000/Alacritty-:0-95485.sock, CONDA_SHLVL=0, XDG_SESSION_CLASS=user, GDM_LANG=en_US.utf8, GTK3_MODULES=xapp-gtk3-module, LSCOLORS=Gxfxcxdxbxegedabagacad, XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/bumpsh, DESKTOP_SESSION=i3, USER=bumpsh, XDG_SEAT=seat0, SSH_AUTH_SOCK=/tmp/ssh-XXXXXXnNT1j3/agent.4100, EDITOR=/usr/bin/nano, HOSTNAME=fedora, ALACRITTY_WINDOW_ID=16777218, XDG_RUNTIME_DIR=/run/user/1000, XDG_VTNR=1, HOME=/home/bumpsh}
    Home directory: /home/bumpsh/.local/share/minosoft
    Config directory: /home/bumpsh/.config/minosoft

-- System information --
    Operating system: Linux: Fedora 64bit
    Platform os: linux
    Platform architecture: amd64
    Java: 11.0.20+8 64bit
    Memory: 62 GiB
    Processor: 16x AMD Ryzen 7 5800H with Radeon Graphics

-- Graphic Cards --
    #0
        Name: GA107BM [GeForce RTX 3050 Ti Mobile]
        Device id: 0x25e0
        VRam: 4328521728
        Vendor: NVIDIA Corporation (0x10de)
        Version info: unknown

-- Connections --
    #0
        Id: 1
        Version: 1.12.2
        Account: Bumpsh
        Address: 127.0.0.1
        Brand: unknown
        Events: 3
        State: ERROR
        DefaultPacketMapping state: HANDSHAKE
        Compression threshold: -1
        Encrypted: false
        Was connected: false
        Rendering: false
        Error: java.lang.NullPointerException

-- Properties --
    Version name: ae7b15d
    Stable: false

-- Git --
    Commit: ae7b15de10be579ca6add2e4078e48b9dfdfb7f3
    Branch: master
    Dirty: false

**Comment by Bixilon** [comment]
Interestingly, are there any other exceptions in the console before?

Could be a duplicate of #22, 1.12.2 is using minosoft-meta instead of pixlyzer. Could be, that the download/loading failed.

Should crash with a different error.


(entity type player not found)
