### ISSUE TITLE
Want to contribute stumbled upon a question

### ISSUE THREAD

**Issue by janareddyc7** [Bixilon/Minosoft#28]
Hi i Want to contribute to this amazing project 

stumbled upon a question how do i run it is  there any environment variables   , could you pls tell me in steps how could i run it wht to install  to contribute thanks

**Comment by Bixilon** [comment]
Read the readme.

**Comment by janareddyc7** [comment]
i tried the readme but it didnt work

**Comment by Bixilon** [comment]
Then provide more context. If you are on windows, use the updater branch (contains important bugfix)
