### ISSUE TITLE
Chunk reading issues keep going

### ISSUE THREAD

**Issue by ilkerbey-01** [Bixilon/Minosoft#5]
https://paste.ee/p/kBOMA

**Comment by ilkerbey-01** [comment]
https://i.imgur.com/0EPgjXi.png

**Comment by Bixilon** [comment]
Actually I started to see issues in 1.17 in the nether, but that is probably not related

**Comment by Bixilon** [comment]
Actually it could be fixed with fe35f3fed31587eab0e033ae69e61df7d09ba85c, can you try again? (let's say maybe)

**Comment by Bixilon** [comment]
> https://i.imgur.com/0EPgjXi.png
it acutally could be related to GH-6

**Comment by Bixilon** [comment]
> https://i.imgur.com/0EPgjXi.png

Should be fixed in `work/light` branch

**Comment by Bixilon** [comment]
Should be fixed now.

**Comment by Bixilon** [comment]
I cherry picked the fix, I also added 2 tests for it in the secret branch
